export const ATTEMPT_DURATION_SECONDS = 3;
export const ATTEMPT_DURATION_MS = ATTEMPT_DURATION_SECONDS * 1000;

export const GENERIC_ATTEMPT_DURATION_MIN_SECONDS = 1;
export const GENERIC_ATTEMPT_DURATION_MAX_SECONDS = 15;
export const GENERIC_ATTEMPT_DURATION_DEFAULT_SECONDS = 3;

export const COUNTDOWN_LABELS = ['3', '2', '1', 'GO'] as const;

export const REFERENCE_MEDIA_ASPECT_RATIO = 16 / 9;
export const CAMERA_MEDIA_ASPECT_RATIO = 3 / 4;
